kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: api-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cherry-awesome-app
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: nginx
