affinity: {}
applicationResources: {}
deploymentEnv:
  APP_PORT: "3000"
  APP_SECRET_TOKEN: /etc/cgr-forms-secrets/app_secret_token
  APP_SECRET_TOKEN_BASE: /etc/cgr-forms-secrets/app_secret_token_base
  AWS_REGION: ap-southeast-2
  CLAMAV_HOST: clamav
  CLAMAV_PORT: "3310"
  DATABASE_POSTGRES_COLLATION: en_US.utf8
  DATABASE_POSTGRES_CTYPE: en_US.utf8
  DATABASE_POSTGRES_ENCODING: utf8
  DATABASE_POSTGRES_HOST: postgres
  DATABASE_POSTGRES_LOCALE: en_US.utf8
  DATABASE_POSTGRES_PASSWORD: /etc/cgr-forms-secrets/database_postgres_password
  DATABASE_POSTGRES_POOL: "6"
  DATABASE_POSTGRES_PORT: "5432"
  DATABASE_POSTGRES_READONLY_PASSWORD: /etc/cgr-forms-secrets/database_postgres_readonly_password
  DATABASE_POSTGRES_READONLY_USERNAME: readonly_cgr_forms
  DATABASE_POSTGRES_TEST_USERNAME: xxx
  DATABASE_POSTGRES_TEST_PASSWORD: xxx
  DATABASE_POSTGRES_TEMPLATE: template0
  DATABASE_POSTGRES_TIMEOUT: "5000"
  DATABASE_POSTGRES_USERNAME: cgr_forms
  DATABASE_PREPARED_STATEMENTS: "True"
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "True"
  RAILS_SERVE_STATIC_FILES: "True"
  RECAPTCHA_SECRET_KEY: /etc/cgr-forms-secrets/recaptcha_secret_key
  RECAPTCHA_SITE_KEY: /etc/cgr-forms-secrets/recaptcha_site_key
  SENTRY_DSN: https://xxx
  STORAGE_SERVICE: aws
  STORAGE_SERVICE_S3_ACCESS_KEY: ""
  STORAGE_SERVICE_S3_BUCKET: xxx
  STORAGE_SERVICE_S3_ENDPOINT: https://s3-ap-southeast-2.amazonaws.com
  STORAGE_SERVICE_S3_REGION: ap-southeast-2
  STORAGE_SERVICE_S3_SECRET_ACCESS_KEY: ""
  WORKER_METHOD: redis
  WORKER_REDIS_DATABASE: ""
  WORKER_REDIS_HOST: redis:6379
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: 014705677267.dkr.ecr.ap-southeast-2.amazonaws.com/cgr-forms
  tag: latest
imagePullSecrets:
  - name: awsecr-cred
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  # fsGroup: 65534
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - all
    add:
    - IPC_LOCK
  runAsGroup: 5062
  runAsUser: 5062
service:
  port: 3000
  type: NodePort
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::014705677267:role/CGRFServiceRoleB
  create: true
  name: cgr-forms
tolerations: []
workerResources:
  limits:
    memory: 1500Mi
  requests:
    memory: 900Mi

applicationResources:
  limits:
    memory: 950Mi
  requests:
    memory: 500Mi

vault:
  vaultRoleName: cgr-forms
  vaultAuthEndpoint: "auth/kubernetes"
  image: vault
  tag: 1.13.3
  pullPolicy: IfNotPresent

