kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  extraMounts:
  - hostPath: /Users/kwantan/cert/ca.pem
    containerPath: /etc/kubernetes/pki/key.pem
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
